<a href="https://colab.research.google.com/github/AnupJoseph/adv-python/blob/master/best_Practices_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

import pandas as pd
import sqlite3

In [2]:
# Useful cell to add a top of every datascience notebook
pd.options.display.max_columns = 1000
pd.options.display.max_rows = 500

In [3]:
!mkdir data

In [4]:
!unzip -d data/ 378_785_bundle_archive.zip

Archive:  378_785_bundle_archive.zip
  inflating: data/imdb.csv

In [ ]:
# lets use this test set

In [6]:
# For reading CSV data
df = pd.read_csv('data/imdb.csv',error_bad_lines=False)

b'Skipping line 66: expected 44 fields, saw 46\nSkipping line 111: expected 44 fields, saw 45\nSkipping line 198: expected 44 fields, saw 45\nSkipping line 222: expected 44 fields, saw 46\nSkipping line 278: expected 44 fields, saw 45\nSkipping line 396: expected 44 fields, saw 45\nSkipping line 403: expected 44 fields, saw 45\nSkipping line 421: expected 44 fields, saw 45\nSkipping line 437: expected 44 fields, saw 45\nSkipping line 462: expected 44 fields, saw 46\nSkipping line 491: expected 44 fields, saw 45\nSkipping line 515: expected 44 fields, saw 45\nSkipping line 529: expected 44 fields, saw 45\nSkipping line 530: expected 44 fields, saw 45\nSkipping line 558: expected 44 fields, saw 45\nSkipping line 623: expected 44 fields, saw 45\nSkipping line 646: expected 44 fields, saw 45\nSkipping line 663: expected 44 fields, saw 46\nSkipping line 713: expected 44 fields, saw 45\nSkipping line 730: expected 44 fields, saw 47\nSkipping line 791: expected 44 fields, saw 45\nSkipping line 813: expected 44 fields, saw 45\nSkipping line 837: expected 44 fields, saw 45\nSkipping line 861: expected 44 fields, saw 45\nSkipping line 874: expected 44 fields, saw 45\nSkipping line 899: expected 44 fields, saw 45\nSkipping line 917: expected 44 fields, saw 45\nSkipping line 944: expected 44 fields, saw 46\nSkipping line 994: expected 44 fields, saw 45\nSkipping line 1027: expected 44 fields, saw 45\nSkipping line 1046: expected 44 fields, saw 45\nSkipping line 1097: expected 44 fields, saw 45\nSkipping line 1106: expected 44 fields, saw 45\nSkipping line 1170: expected 44 fields, saw 45\nSkipping line 1194: expected 44 fields, saw 45\nSkipping line 1195: expected 44 fields, saw 45\nSkipping line 1218: expected 44 fields, saw 45\nSkipping line 1220: expected 44 fields, saw 45\nSkipping line 1270: expected 44 fields, saw 45\nSkipping line 1338: expected 44 fields, saw 47\nSkipping line 1355: expected 44 fields, saw 45\nSkipping line 1363: expected 44 fields, saw 45\nSkipping line 1395: expected 44 fields, saw 45\nSkipping line 1402: expected 44 fields, saw 46\nSkipping line 1418: expected 44 fields, saw 45\nSkipping line 1431: expected 44 fields, saw 45\nSkipping line 1617: expected 44 fields, saw 45\nSkipping line 1663: expected 44 fields, saw 45\nSkipping line 1742: expected 44 fields, saw 46\nSkipping line 1766: expected 44 fields, saw 45\nSkipping line 1799: expected 44 fields, saw 45\nSkipping line 1867: expected 44 fields, saw 45\nSkipping line 1899: expected 44 fields, saw 45\nSkipping line 1900: expected 44 fields, saw 45\nSkipping line 1901: expected 44 fields, saw 45\nSkipping line 1907: expected 44 fields, saw 45\nSkipping line 1913: expected 44 fields, saw 45\nSkipping line 1924: expected 44 fields, saw 45\nSkipping line 1939: expected 44 fields, saw 45\nSkipping line 1945: expected 44 fields, saw 45\nSkipping line 1982: expected 44 fields, saw 45\nSkipping line 2023: expected 44 fields, saw 45\nSkipping line 2028: expected 44 fields, saw 45\nSkipping line 2054: expected 44 fields, saw 45\nSkipping line 2076: expected 44 fields, saw 45\nSkipping line 2081: expected 44 fields, saw 45\nSkipping line 2092: expected 44 fields, saw 45\nSkipping line 2107: expected 44 fields, saw 45\nSkipping line 2160: expected 44 fields, saw 45\nSkipping line 2260: expected 44 fields, saw 45\nSkipping line 2261: expected 44 fields, saw 45\nSkipping line 2289: expected 44 fields, saw 46\nSkipping line 2290: expected 44 fields, saw 45\nSkipping line 2349: expected 44 fields, saw 45\nSkipping line 2395: expected 44 fields, saw 45\nSkipping line 2507: expected 44 fields, saw 45\nSkipping line 2584: expected 44 fields, saw 45\nSkipping line 2588: expected 44 fields, saw 46\nSkipping line 2595: expected 44 fields, saw 45\nSkipping line 2604: expected 44 fields, saw 45\nSkipping line 2622: expected 44 fields, saw 45\nSkipping line 2661: expected 44 fields, saw 45\nSkipping line 2714: expected 44 fields, saw 45\nSkipping line 2722: expected 44 fields, saw 45\nSkipping line 2776: expected 44 fields, saw 45\nSkipping line 2806: expected 44 fields, saw 45\nSkipping line 2826: expected 44 fields, saw 45\nSkipping line 2882: expected 44 fields, saw 45\nSkipping line 2909: expected 44 fields, saw 45\nSkipping line 3005: expected 44 fields, saw 45\nSkipping line 3019: expected 44 fields, saw 45\nSkipping line 3052: expected 44 fields, saw 45\nSkipping line 3062: expected 44 fields, saw 45\nSkipping line 3086: expected 44 fields, saw 45\nSkipping line 3089: expected 44 fields, saw 45\nSkipping line 3134: expected 44 fields, saw 46\nSkipping line 3157: expected 44 fields, saw 45\nSkipping line 3163: expected 44 fields, saw 45\nSkipping line 3177: expected 44 fields, saw 45\nSkipping line 3190: expected 44 fields, saw 45\nSkipping line 3205: expected 44 fields, saw 45\nSkipping line 3209: expected 44 fields, saw 45\nSkipping line 3238: expected 44 fields, saw 45\nSkipping line 3242: expected 44 fields, saw 45\nSkipping line 3255: expected 44 fields, saw 45\nSkipping line 3303: expected 44 fields, saw 45\nSkipping line 3314: expected 44 fields, saw 45\nSkipping line 3322: expected 44 fields, saw 45\nSkipping line 3358: expected 44 fields, saw 45\nSkipping line 3360: expected 44 fields, saw 46\nSkipping line 3377: expected 44 fields, saw 45\nSkipping line 3413: expected 44 fields, saw 45\nSkipping line 3481: expected 44 fields, saw 45\nSkipping line 3496: expected 44 fields, saw 45\nSkipping line 3719: expected 44 fields, saw 45\nSkipping line 3792: expected 44 fields, saw 45\nSkipping line 3807: expected 44 fields, saw 46\nSkipping line 3858: expected 44 fields, saw 45\nSkipping line 3864: expected 44 fields, saw 45\nSkipping line 3902: expected 44 fields, saw 45\nSkipping line 3943: expected 44 fields, saw 45\nSkipping line 3969: expected 44 fields, saw 45\nSkipping line 4024: expected 44 fields, saw 47\nSkipping line 4044: expected 44 fields, saw 45\nSkipping line 4045: expected 44 fields, saw 45\nSkipping line 4112: expected 44 fields, saw 45\nSkipping line 4149: expected 44 fields, saw 45\nSkipping line 4280: expected 44 fields, saw 45\nSkipping line 4282: expected 44 fields, saw 45\nSkipping line 4308: expected 44 fields, saw 45\nSkipping line 4377: expected 44 fields, saw 45\nSkipping line 4390: expected 44 fields, saw 45\nSkipping line 4404: expected 44 fields, saw 45\nSkipping line 4416: expected 44 fields, saw 45\nSkipping line 4423: expected 44 fields, saw 46\nSkipping line 4540: expected 44 fields, saw 45\nSkipping line 4554: expected 44 fields, saw 45\nSkipping line 4556: expected 44 fields, saw 46\nSkipping line 4572: expected 44 fields, saw 45\nSkipping line 4593: expected 44 fields, saw 45\nSkipping line 4614: expected 44 fields, saw 45\nSkipping line 4688: expected 44 fields, saw 45\nSkipping line 4750: expected 44 fields, saw 45\nSkipping line 4764: expected 44 fields, saw 45\nSkipping line 4765: expected 44 fields, saw 45\nSkipping line 4849: expected 44 fields, saw 45\nSkipping line 4865: expected 44 fields, saw 45\nSkipping line 4892: expected 44 fields, saw 45\nSkipping line 4893: expected 44 fields, saw 45\nSkipping line 4897: expected 44 fields, saw 45\nSkipping line 4923: expected 44 fields, saw 45\nSkipping line 4956: expected 44 fields, saw 45\nSkipping line 4957: expected 44 fields, saw 45\nSkipping line 4962: expected 44 fields, saw 45\nSkipping line 4967: expected 44 fields, saw 45\nSkipping line 4971: expected 44 fields, saw 45\nSkipping line 5057: expected 44 fields, saw 45\nSkipping line 5061: expected 44 fields, saw 45\nSkipping line 5097: expected 44 fields, saw 45\nSkipping line 5125: expected 44 fields, saw 45\nSkipping line 5180: expected 44 fields, saw 45\nSkipping line 5207: expected 44 fields, saw 45\nSkipping line 5339: expected 44 fields, saw 45\nSkipping line 5426: expected 44 fields, saw 45\nSkipping line 5474: expected 44 fields, saw 45\nSkipping line 5511: expected 44 fields, saw 45\nSkipping line 5561: expected 44 fields, saw 45\nSkipping line 5563: expected 44 fields, saw 45\nSkipping line 5689: expected 44 fields, saw 45\nSkipping line 5725: expected 44 fields, saw 45\nSkipping line 5759: expected 44 fields, saw 45\nSkipping line 5796: expected 44 fields, saw 45\nSkipping line 5829: expected 44 fields, saw 45\nSkipping line 5854: expected 44 fields, saw 45\nSkipping line 5886: expected 44 fields, saw 45\nSkipping line 5899: expected 44 fields, saw 45\nSkipping line 5901: expected 44 fields, saw 45\nSkipping line 5970: expected 44 fields, saw 45\nSkipping line 5996: expected 44 fields, saw 45\nSkipping line 6085: expected 44 fields, saw 45\nSkipping line 6087: expected 44 fields, saw 45\nSkipping line 6095: expected 44 fields, saw 45\nSkipping line 6096: expected 44 fields, saw 45\nSkipping line 6098: expected 44 fields, saw 45\nSkipping line 6115: expected 44 fields, saw 46\nSkipping line 6158: expected 44 fields, saw 46\nSkipping line 6174: expected 44 fields, saw 45\nSkipping line 6187: expected 44 fields, saw 45\nSkipping line 6218: expected 44 fields, saw 45\nSkipping line 6266: expected 44 fields, saw 45\nSkipping line 6275: expected 44 fields, saw 45\nSkipping line 6279: expected 44 fields, saw 45\nSkipping line 6296: expected 44 fields, saw 45\nSkipping line 6471: expected 44 fields, saw 46\nSkipping line 6494: expected 44 fields, saw 45\nSkipping line 6497: expected 44 fields, saw 45\nSkipping line 6614: expected 44 fields, saw 46\nSkipping line 6714: expected 44 fields, saw 45\nSkipping line 6727: expected 44 fields, saw 45\nSkipping line 6752: expected 44 fields, saw 45\nSkipping line 6763: expected 44 fields, saw 45\nSkipping line 6817: expected 44 fields, saw 45\nSkipping line 6853: expected 44 fields, saw 45\nSkipping line 6904: expected 44 fields, saw 45\nSkipping line 6914: expected 44 fields, saw 45\nSkipping line 6948: expected 44 fields, saw 45\nSkipping line 6969: expected 44 fields, saw 45\nSkipping line 6979: expected 44 fields, saw 45\nSkipping line 7010: expected 44 fields, saw 47\nSkipping line 7024: expected 44 fields, saw 45\nSkipping line 7036: expected 44 fields, saw 45\nSkipping line 7069: expected 44 fields, saw 45\nSkipping line 7146: expected 44 fields, saw 45\nSkipping line 7168: expected 44 fields, saw 45\nSkipping line 7170: expected 44 fields, saw 45\nSkipping line 7317: expected 44 fields, saw 45\nSkipping line 7399: expected 44 fields, saw 45\nSkipping line 7402: expected 44 fields, saw 45\nSkipping line 7496: expected 44 fields, saw 45\nSkipping line 7584: expected 44 fields, saw 45\nSkipping line 7666: expected 44 fields, saw 45\nSkipping line 7690: expected 44 fields, saw 45\nSkipping line 7704: expected 44 fields, saw 47\nSkipping line 7738: expected 44 fields, saw 45\nSkipping line 7773: expected 44 fields, saw 45\nSkipping line 7803: expected 44 fields, saw 45\nSkipping line 7839: expected 44 fields, saw 45\nSkipping line 7850: expected 44 fields, saw 45\nSkipping line 7910: expected 44 fields, saw 45\nSkipping line 7942: expected 44 fields, saw 45\nSkipping line 7959: expected 44 fields, saw 45\nSkipping line 8024: expected 44 fields, saw 45\nSkipping line 8026: expected 44 fields, saw 45\nSkipping line 8028: expected 44 fields, saw 45\nSkipping line 8033: expected 44 fields, saw 45\nSkipping line 8052: expected 44 fields, saw 45\nSkipping line 8129: expected 44 fields, saw 45\nSkipping line 8138: expected 44 fields, saw 45\nSkipping line 8160: expected 44 fields, saw 46\nSkipping line 8244: expected 44 fields, saw 45\nSkipping line 8255: expected 44 fields, saw 45\nSkipping line 8390: expected 44 fields, saw 45\nSkipping line 8400: expected 44 fields, saw 45\nSkipping line 8429: expected 44 fields, saw 45\nSkipping line 8446: expected 44 fields, saw 46\nSkipping line 8565: expected 44 fields, saw 46\nSkipping line 8622: expected 44 fields, saw 46\nSkipping line 8658: expected 44 fields, saw 45\nSkipping line 8742: expected 44 fields, saw 45\nSkipping line 8748: expected 44 fields, saw 45\nSkipping line 8802: expected 44 fields, saw 45\nSkipping line 8844: expected 44 fields, saw 45\nSkipping line 8874: expected 44 fields, saw 45\nSkipping line 8882: expected 44 fields, saw 45\nSkipping line 8885: expected 44 fields, saw 48\nSkipping line 8910: expected 44 fields, saw 45\nSkipping line 8923: expected 44 fields, saw 45\nSkipping line 8947: expected 44 fields, saw 45\nSkipping line 8958: expected 44 fields, saw 45\nSkipping line 9039: expected 44 fields, saw 46\nSkipping line 9090: expected 44 fields, saw 45\nSkipping line 9112: expected 44 fields, saw 45\nSkipping line 9137: expected 44 fields, saw 45\nSkipping line 9201: expected 44 fields, saw 45\nSkipping line 9257: expected 44 fields, saw 45\nSkipping line 9272: expected 44 fields, saw 45\nSkipping line 9390: expected 44 fields, saw 45\nSkipping line 9487: expected 44 fields, saw 45\nSkipping line 9518: expected 44 fields, saw 45\nSkipping line 9554: expected 44 fields, saw 45\nSkipping line 9576: expected 44 fields, saw 45\nSkipping line 9671: expected 44 fields, saw 45\nSkipping line 9690: expected 44 fields, saw 45\nSkipping line 9758: expected 44 fields, saw 45\nSkipping line 9759: expected 44 fields, saw 45\nSkipping line 9767: expected 44 fields, saw 45\nSkipping line 9776: expected 44 fields, saw 45\nSkipping line 9805: expected 44 fields, saw 45\nSkipping line 9834: expected 44 fields, saw 45\nSkipping line 9837: expected 44 fields, saw 45\nSkipping line 9854: expected 44 fields, saw 45\nSkipping line 9890: expected 44 fields, saw 45\nSkipping line 9897: expected 44 fields, saw 45\nSkipping line 9957: expected 44 fields, saw 45\nSkipping line 9979: expected 44 fields, saw 45\nSkipping line 9980: expected 44 fields, saw 45\nSkipping line 10001: expected 44 fields, saw 45\nSkipping line 10002: expected 44 fields, saw 45\nSkipping line 10023: expected 44 fields, saw 45\nSkipping line 10032: expected 44 fields, saw 45\nSkipping line 10051: expected 44 fields, saw 45\nSkipping line 10059: expected 44 fields, saw 46\nSkipping line 10086: expected 44 fields, saw 45\nSkipping line 10102: expected 44 fields, saw 45\nSkipping line 10118: expected 44 fields, saw 45\nSkipping line 10184: expected 44 fields, saw 45\nSkipping line 10199: expected 44 fields, saw 45\nSkipping line 10204: expected 44 fields, saw 45\nSkipping line 10218: expected 44 fields, saw 45\nSkipping line 10224: expected 44 fields, saw 45\nSkipping line 10294: expected 44 fields, saw 45\nSkipping line 10296: expected 44 fields, saw 45\nSkipping line 10331: expected 44 fields, saw 45\nSkipping line 10342: expected 44 fields, saw 45\nSkipping line 10351: expected 44 fields, saw 45\nSkipping line 10414: expected 44 fields, saw 45\nSkipping line 10430: expected 44 fields, saw 45\nSkipping line 10463: expected 44 fields, saw 45\nSkipping line 10478: expected 44 fields, saw 46\nSkipping line 10533: expected 44 fields, saw 45\nSkipping line 10536: expected 44 fields, saw 45\nSkipping line 10539: expected 44 fields, saw 45\nSkipping line 10549: expected 44 fields, saw 45\nSkipping line 10582: expected 44 fields, saw 45\nSkipping line 10588: expected 44 fields, saw 45\nSkipping line 10598: expected 44 fields, saw 45\nSkipping line 10660: expected 44 fields, saw 45\nSkipping line 10733: expected 44 fields, saw 45\nSkipping line 10806: expected 44 fields, saw 45\nSkipping line 10862: expected 44 fields, saw 45\nSkipping line 10905: expected 44 fields, saw 45\nSkipping line 10993: expected 44 fields, saw 45\nSkipping line 11070: expected 44 fields, saw 45\nSkipping line 11084: expected 44 fields, saw 45\nSkipping line 11110: expected 44 fields, saw 45\nSkipping line 11123: expected 44 fields, saw 45\nSkipping line 11128: expected 44 fields, saw 45\nSkipping line 11129: expected 44 fields, saw 45\nSkipping line 11196: expected 44 fields, saw 45\nSkipping line 11210: expected 44 fields, saw 45\nSkipping line 11254: expected 44 fields, saw 45\nSkipping line 11290: expected 44 fields, saw 45\nSkipping line 11365: expected 44 fields, saw 45\nSkipping line 11433: expected 44 fields, saw 45\nSkipping line 11434: expected 44 fields, saw 45\nSkipping line 11469: expected 44 fields, saw 45\nSkipping line 11475: expected 44 fields, saw 45\nSkipping line 11480: expected 44 fields, saw 45\nSkipping line 11513: expected 44 fields, saw 45\nSkipping line 11522: expected 44 fields, saw 45\nSkipping line 11553: expected 44 fields, saw 45\nSkipping line 11610: expected 44 fields, saw 45\nSkipping line 11641: expected 44 fields, saw 45\nSkipping line 11655: expected 44 fields, saw 46\nSkipping line 11689: expected 44 fields, saw 45\nSkipping line 11753: expected 44 fields, saw 45\nSkipping line 11776: expected 44 fields, saw 45\nSkipping line 11797: expected 44 fields, saw 45\nSkipping line 11809: expected 44 fields, saw 45\nSkipping line 11882: expected 44 fields, saw 45\nSkipping line 11915: expected 44 fields, saw 45\nSkipping line 11917: expected 44 fields, saw 46\nSkipping line 11929: expected 44 fields, saw 45\nSkipping line 11956: expected 44 fields, saw 45\nSkipping line 12031: expected 44 fields, saw 45\nSkipping line 12047: expected 44 fields, saw 46\nSkipping line 12160: expected 44 fields, saw 45\nSkipping line 12180: expected 44 fields, saw 45\nSkipping line 12184: expected 44 fields, saw 45\nSkipping line 12224: expected 44 fields, saw 45\nSkipping line 12227: expected 44 fields, saw 45\nSkipping line 12233: expected 44 fields, saw 45\nSkipping line 12251: expected 44 fields, saw 45\nSkipping line 12256: expected 44 fields, saw 45\nSkipping line 12257: expected 44 fields, saw 45\nSkipping line 12259: expected 44 fields, saw 45\nSkipping line 12355: expected 44 fields, saw 45\nSkipping line 12378: expected 44 fields, saw 45\nSkipping line 12398: expected 44 fields, saw 45\nSkipping line 12486: expected 44 fields, saw 45\nSkipping line 12516: expected 44 fields, saw 45\nSkipping line 12588: expected 44 fields, saw 45\nSkipping line 12595: expected 44 fields, saw 45\nSkipping line 12614: expected 44 fields, saw 45\nSkipping line 12642: expected 44 fields, saw 45\nSkipping line 12701: expected 44 fields, saw 45\nSkipping line 12741: expected 44 fields, saw 46\nSkipping line 12771: expected 44 fields, saw 45\nSkipping line 12777: expected 44 fields, saw 45\nSkipping line 12802: expected 44 fields, saw 45\nSkipping line 12892: expected 44 fields, saw 45\nSkipping line 12910: expected 44 fields, saw 47\nSkipping line 12982: expected 44 fields, saw 46\nSkipping line 13024: expected 44 fields, saw 45\nSkipping line 13052: expected 44 fields, saw 45\nSkipping line 13056: expected 44 fields, saw 45\nSkipping line 13158: expected 44 fields, saw 45\nSkipping line 13170: expected 44 fields, saw 45\nSkipping line 13171: expected 44 fields, saw 45\nSkipping line 13186: expected 44 fields, saw 45\nSkipping line 13240: expected 44 fields, saw 45\nSkipping line 13262: expected 44 fields, saw 45\nSkipping line 13374: expected 44 fields, saw 45\nSkipping line 13407: expected 44 fields, saw 45\nSkipping line 13477: expected 44 fields, saw 45\nSkipping line 13540: expected 44 fields, saw 46\nSkipping line 13569: expected 44 fields, saw 45\nSkipping line 13617: expected 44 fields, saw 46\nSkipping line 13651: expected 44 fields, saw 45\nSkipping line 13663: expected 44 fields, saw 45\nSkipping line 13754: expected 44 fields, saw 46\nSkipping line 13775: expected 44 fields, saw 45\nSkipping line 13804: expected 44 fields, saw 45\nSkipping line 13828: expected 44 fields, saw 45\nSkipping line 13865: expected 44 fields, saw 46\nSkipping line 13883: expected 44 fields, saw 45\nSkipping line 13929: expected 44 fields, saw 45\nSkipping line 13948: expected 44 fields, saw 45\nSkipping line 14022: expected 44 fields, saw 45\nSkipping line 14127: expected 44 fields, saw 45\nSkipping line 14148: expected 44 fields, saw 45\nSkipping line 14173: expected 44 fields, saw 45\nSkipping line 14243: expected 44 fields, saw 45\nSkipping line 14254: expected 44 fields, saw 45\nSkipping line 14318: expecte

In [ ]:
# For reading SQL data, (I am using sqlite here as I have the sqlite file in this repo)

# Create a connection to the sqlite database
def create_connection(path):
  connection = None

  # Always use try catch blocks for connecting to databases.
  # They have ways of throwing up the most awkward error messages ever written
  try:
    connection = sqlite3.connect(path)
    print(f"Connection to DB successful")
  except Error as e:
    print(f"The Error {e} occured")

  return connection

connection = create_connection("data/db.sqlite")
query = "SELECT * FROM users"
df_sql = pd.read_sql(query,connection)

In [10]:
# Basic data snapshots
print(df.head(10))
print(df.tail(10))

                   fn        tid                                  title  \
0  titles01/tt0012349  tt0012349       Der Vagabund und das Kind (1921)
1  titles01/tt0015864  tt0015864                      Goldrausch (1925)
2  titles01/tt0017136  tt0017136                      Metropolis (1927)
3  titles01/tt0017925  tt0017925                     Der General (1926)
4  titles01/tt0021749  tt0021749           Lichter der Großstadt (1931)
5  titles01/tt0022100  tt0022100                               M (1931)
6  titles01/tt0025316  tt0025316       Es geschah in einer Nacht (1934)
7  titles01/tt0027977  tt0027977                  Moderne Zeiten (1936)
8  titles01/tt0031381  tt0031381               Vom Winde verweht (1939)
9  titles01/tt0031679  tt0031679  Mr. Smith geht nach Washington (1939)

                    wordsInTitle                                   url  \
0      der vagabund und das kind  http://www.imdb.com/title/tt0012349/
1                     goldrausch  http://www.imdb.com/title/tt0015864/
2                     metropolis  http://www.imdb.com/title/tt0017136/
3                    der general  http://www.imdb.com/title/tt0017925/
4          lichter der gro stadt  http://www.imdb.com/title/tt0021749/
5                              m  http://www.imdb.com/title/tt0022100/
6      es geschah in einer nacht  http://www.imdb.com/title/tt0025316/
7                 moderne zeiten  http://www.imdb.com/title/tt0027977/
8              vom winde verweht  http://www.imdb.com/title/tt0031381/
9  mr smith geht nach washington  http://www.imdb.com/title/tt0031679/

   imdbRating  ratingCount  duration    year         type  nrOfWins  \
0         8.4      40550.0    3240.0  1921.0  video.movie         1
1         8.3      45319.0    5700.0  1925.0  video.movie         2
2         8.4      81007.0    9180.0  1927.0  video.movie         3
3         8.3      37521.0    6420.0  1926.0  video.movie         1
4         8.7      70057.0    5220.0  1931.0  video.movie         2
5         8.5      73726.0    7020.0  1931.0  video.movie         1
6         8.3      46503.0    6300.0  1934.0  video.movie         4
7         8.6      90847.0    5220.0  1936.0  video.movie         3
8         8.2     160414.0   14280.0  1939.0  video.movie        10
9         8.4      58169.0    7740.0  1939.0  video.movie         4

   nrOfNominations  nrOfPhotos  nrOfNewsArticles  nrOfUserReviews  nrOfGenre  \
0                0          19                96               85          3
1                1          35               110              122          3
2                4          67               428              376          2
3                1          53               123              219          3
4                0          38               187              186          3
5                0          28                 4              254          3
6                1          40               183              211          2
7                1          44                27              180          2
8                6         143              1263              653          3
9               10          34               110              226          1

   Action  Adult  Adventure  Animation  Biography  Comedy  Crime  Documentary  \
0       0      0          0          0          0       1      0            0
1       0      0          1          0          0       1      0            0
2       0      0          0          0          0       0      0            0
3       1      0          1          0          0       1      0            0
4       0      0          0          0          0       1      0            0
5       0      0          0          0          0       0      1            0
6       0      0          0          0          0       1      0            0
7       0      0          0          0          0       1      0            0
8       0      0          0          0          0       0      0            0
9       0      0          0          0          0       0      0            0

   Drama  Family  Fantasy  FilmNoir  GameShow  History  Horror  Music  \
0      1       1        0         0         0        0       0      0
1      0       1        0         0         0        0       0      0
2      1       0        0         0         0        0       0      0
3      0       0        0         0         0        0       0      0
4      1       0        0         0         0        0       0      0
5      1       0        0         0         0        0       0      0
6      0       0        0         0         0        0       0      0
7      1       0        0         0         0        0       0      0
8      1       0        0         0         0        0       0      0
9      1       0        0         0         0        0       0      0

   Musical  Mystery  News  RealityTV  Romance  SciFi  Short  Sport  TalkShow  \
0        0        0     0          0        0      0      0      0         0
1        0        0     0          0        0      0      0      0         0
2        0        0     0          0        0      1      0      0         0
3        0        0     0          0        0      0      0      0         0
4        0        0     0          0        1      0      0      0         0
5        0        0     0          0        0      0      0      0         0
6        0        0     0          0        1      0      0      0         0
7        0        0     0          0        0      0      0      0         0
8        0        0     0          0        1      0      0      0         0
9        0        0     0          0        0      0      0      0         0

   Thriller  War  Western
0         0    0        0
1         0    0        0
2         0    0        0
3         0    0        0
4         0    0        0
5         1    0        0
6         0    0        0
7         0    0        0
8         0    1        0
9         0    0        0
                             fn        tid  \
14322  titles04/index.html.9980  tt0659108
14323  titles04/index.html.9982  tt0659943
14324  titles04/index.html.9984  tt0664265
14325  titles04/index.html.9986  tt0666595
14326  titles04/index.html.9987  tt0669703
14327  titles04/index.html.9989  tt0672488
14328  titles04/index.html.9992  tt0675644
14329  titles04/index.html.9994  tt0679222
14330  titles04/index.html.9995  tt0680064
14331  titles04/index.html.9997  tt0681024

                                                   title  \
14322  Never Mind the Buzzcocks Episode #9.6 (TV Epis...
14323   Newhart Heaven Knows Mr. Utley (TV Episode 1983)
14324        Männerwirtschaft Password (TV Episode 1972)
14325  Only Fools and Horses.... Yuppy Love (TV Episo...
14326  Parker Lewis - Der Coole von der Schule Parker...
14327             Peep Show Sectioning (TV Episode 2005)
14328  Playhouse 90 The Miracle Worker (TV Episode 1957)
14329  Private Screenings Robert Mitchum and Jane Rus...
14330    Providence All the King's Men (TV Episode 2002)
14331                          QI Adam (TV Episode 2003)

                                            wordsInTitle  \
14322        never mind the buzzcocks episode tv episode
14323           newhart heaven knows mr utley tv episode
14324               m nnerwirtschaft password tv episode
14325        only fools and horses yuppy love tv episode
14326  parker lewis der coole von der schule parker l...
14327                    peep show sectioning tv episode
14328            playhouse the miracle worker tv episode
14329  private screenings robert mitchum and jane rus...
14330           providence all the king s men tv episode
14331                                 qi adam tv episode

                                        url  imdbRating  ratingCount  \
14322  http://www.imdb.com/title/tt0659108/         6.5          6.0
14323  http://www.imdb.com/title/tt0659943/         8.4         14.0
14324  http://www.imdb.com/title/tt0664265/         8.6         47.0
14325  http://www.imdb.com/title/tt0666595/         8.4        154.0
14326  http://www.imdb.com/title/tt0669703/         7.6         16.0
14327  http://www.imdb.com/title/tt0672488/         7.7        135.0
14328  http://www.imdb.com/title/tt0675644/         7.3          8.0
14329  http://www.imdb.com/title/tt0679222/         7.0         20.0
14330  http://www.imdb.com/title/tt0680064/         NaN          NaN
14331  http://www.imdb.com/title/tt0681024/         7.6         89.0

       duration    year           type  nrOfWins  nrOfNominations  nrOfPhotos  \
14322    1800.0  2001.0  video.episode         0                0           0
14323    1800.0  1983.0  video.episode         0                0           0
14324    1800.0  1972.0  video.episode         0                0           0
14325    3000.0  1989.0  video.episode         0                0           0
14326    1800.0  1991.0  video.episode         0                0           0
14327    1440.0  2005.0  video.episode         0                0           0
14328    5400.0  1957.0  video.episode         0                0           0
14329    3600.0  1996.0  video.episode         0                0           0
14330    3600.0  2002.0  video.episode         0                0           0
14331    1800.0  2003.0  video.episode         0                0           0

       nrOfNewsArticles  nrOfUserReviews  nrOfGenre  Action  Adult  Adventure  \
14322                 0                0          3       0      0          0
14323                 0                0          1       0      0          0
14324                 0                0          1       0      0          0
14325                 0                0          2       0      0          0
14326                 0                1          1       0      0          0
14327                 0                0          1       0      0          0
14328                 0                0          3       0      0          0
14329                 0                3          1       0      0          0
14330                 0                0          1       0      0          0
14331                 0                0          2       0      0          0

       Animation  Biography  Comedy  Crime  Documentary  Drama  Family  \
14322          0          0       1      0            0      0       0
14323          0          0       1      0            0      0       0
14324          0          0       1      0            0      0       0
14325          0          0       1      1            0      0       0
14326          0          0       1      0            0      0       0
14327          0          0       1      0            0      0       0
14328          0          0       1      1            0      1       0
14329          0          0       0      0            0      0       0
14330          0          0       0      0            0      1       0
14331          0          0       1      0            0      0       0

       Fantasy  FilmNoir  GameShow  History  Horror  Music  Musical  Mystery  \
14322        0         0         1        0       0      1        0        0
14323        0         0         0        0       0      0        0        0
14324        0         0         0        0       0      0        0        0
14325        0         0         0        0       0      0        0        0
14326        0         0         0        0       0      0        0        0
14327        0         0         0        0       0      0        0        0
14328        0         0         0        0       0      0        0        0
14329        0         0         0        0       0      0        0        0
14330        0         0         0        0       0      0        0        0
14331        0         0         1        0       0      0        0        0

       News  RealityTV  Romance  SciFi  Short  Sport  TalkShow  Thriller  War  \
14322     0          0        0      0      0      0         0         0    0
14323     0          0        0      0      0      0         0         0    0
14324     0          0        0      0      0      0         0         0    0
14325     0          0        0      0      0      0         0         0    0
14326     0          0        0      0      0      0         0         0    0
14327     0          0        0      0      0      0         0         0    0
14328     0          0        0      0      0      0         0         0    0
14329     0          0        0      0      0      0         1         0    0
14330     0          0        0      0      0      0         0         0    0
14331     0          0        0      0      0      0         0         0    0

       Western
14322        0
14323        0
14324        0
14325        0
14326        0
14327        0
14328        0
14329        0
14330        0
14331        0

In [11]:
# To get statistics of numerical columns
df.describe()

,imdbRating,ratingCount,duration,year,nrOfWins,nrOfNominations,nrOfPhotos,nrOfNewsArticles,nrOfUserReviews,nrOfGenre,Action,Adult,Adventure,Animation,Biography,Comedy,Crime,Documentary,Drama,Family,Fantasy,FilmNoir,GameShow,History,Horror,Music,Musical,Mystery,News,RealityTV,Romance,SciFi,Short,Sport,TalkShow,Thriller,War,Western
count,13153.000000,1.315300e+04,13331.000000,14305.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000,14332.000000
mean,6.864198,2.659931e+04,5424.729128,1990.786578,3.104661,4.525119,23.747977,252.545004,103.894013,2.233464,0.156084,0.001954,0.123360,0.069565,0.041934,0.360313,0.138013,0.080031,0.417388,0.072844,0.057563,0.013187,0.012978,0.039632,0.070681,0.037817,0.025467,0.066913,0.011024,0.008722,0.126012,0.067541,0.037887,0.016118,0.036282,0.090357,0.031887,0.021909
std,1.121516,6.558283e+04,2785.490153,22.198970,9.288554,16.038089,66.114012,1065.105124,231.298846,0.828999,0.362948,0.044159,0.328862,0.254421,0.200446,0.480108,0.344925,0.271350,0.493145,0.259889,0.232924,0.114080,0.113183,0.195099,0.256300,0.190761,0.157546,0.249880,0.104420,0.092985,0.331874,0.250966,0.190930,0.125933,0.186999,0.286703,0.175705,0.146392
min,1.000000,5.000000e+00,2.000000,1888.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.300000,6.020000e+02,3720.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.000000,3.990000e+03,5700.000000,1999.000000,0.000000,0.000000,7.000000,8.000000,30.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,7.600000,2.090500e+04,6660.000000,2008.000000,2.000000,3.000000,26.000000,103.000000,103.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.900000,1.183395e+06,68400.000000,2017.000000,226.000000,542.000000,2810.000000,32345.000000,4928.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [14]:
# To get some other basic information

# To get maximum of a column
print(max(df['imdbRating']))

# To get number of rows of a dataframe
print(len(df))

# To get the shape of a dataframe
print(df.shape)

9.9
14332
(14332, 44)

In [15]:
# Always use the [] operator for selecting columns. It makes it a lot more explicit about the dataframe
# Plus the . operator is usually used for object atrributesand functions in Python 
# It doesn't make a lot of sense to change a accepted convention with solid reasons behind it change for the sake of saving a few keystrokes 
df['Biography']

0        0
1        0
2        0
3        0
4        0
        ..
14327    0
14328    0
14329    0
14330    0
14331    0
Name: Biography, Length: 14332, dtype: int64

In [ ]:
# Accessing column names in dataframes
columns = df.columns

# Plus prefer to have not spaces in the column names so I am changing them like so

In [23]:
# Subsetting specific columns
df = df[['imdbRating', 'ratingCount', 'duration', 'year',	'nrOfWins',	'nrOfNominations',	'nrOfPhotos',	'nrOfNewsArticles',	'nrOfUserReviews'	]]